[package]
name = "urlshortner"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.1", default-features = false, features = ["runtime-tokio", "tls-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
serde = { version = "1", features = ["derive"] }
