database:
  driver: "postgres"
  host: "localhost"
  port: 54321 # from docker. check init_db
  username: "postgres"
  password: "password"
  database_name: "newsletter"

url_prefix: "tier.app"
port: 1234
base_url: "localhost"